<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/01_pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})

In [4]:
df.head()

      country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [7]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df["country"].head()

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [8]:
type(df["country"])

pandas.core.series.Series

In [9]:
df[['country']]

      country
0  Kazakhstan
1      Russia
2     Belarus
3     Ukraine

In [10]:
type(df[["country"]])

pandas.core.frame.DataFrame

In [11]:
df2 = pd.DataFrame(
    {
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
    },
    index=['KZ', 'RU', 'BY', 'UA']
)

In [12]:
df2.head()

       country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [13]:
df.index = ['KZ1', 'RU1', 'BY1', 'UA1']

In [14]:
df.head()

        country  population    square
KZ1  Kazakhstan       17.04   2724902
RU1      Russia      143.50  17125191
BY1     Belarus        9.50    207600
UA1     Ukraine       45.50    603628