<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/pandas_readdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [12]:
df = pd.read_csv("simple_data.csv")

In [5]:
! curl -o simple_data.csv https://raw.githubusercontent.com/erkansirin78/datasets/master/simple_data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   592  100   592    0     0   2136      0 --:--:-- --:--:-- --:--:--  2144

In [7]:
df.head()

   sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23          NaN     Bursa         4800

In [9]:
#df şekli boyutu
df.shape

(17, 6)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sirano       17 non-null     int64
 1   isim         17 non-null     object
 2   yas          17 non-null     int64
 3   meslek       15 non-null     object
 4   sehir        17 non-null     object
 5   aylik_gelir  17 non-null     int64
dtypes: int64(3), object(3)
memory usage: 948.0+ bytes

In [13]:
df2 = pd.read_csv("simple_data.csv", sep=",", usecols=['sirano','isim'])

In [14]:
df2.head()

   sirano     isim
0       1    Cemal
1       2    Ceyda
2       3    Timur
3       4    Burcu
4       5  Yasemin

In [17]:
df2 = pd.read_csv("simple_data.csv", sep=";")

In [18]:
df2.head()

  sirano,isim,yas,meslek,sehir,aylik_gelir
0              1,Cemal,35,Isci,Ankara,3500
1            2,Ceyda,42,Memur,Kayseri,4200
2        3,Timur,30,Müzisyen,Istanbul,9000
3       4,Burcu,29,Pazarlamaci,Ankara,4200
4                 5,Yasemin,23,,Bursa,4800

In [19]:
df.columns

Index(['sirano', 'isim', 'yas', 'meslek', 'sehir', 'aylik_gelir'], dtype='object')

In [20]:
new_cols = ['sirano', 'ad', 'yas', 'meslek', 'sehir', 'aylikgelir']

In [21]:
df.columns = new_cols

In [22]:
df.head()

   sirano       ad  yas       meslek     sehir  aylikgelir
0       1    Cemal   35         Isci    Ankara        3500
1       2    Ceyda   42        Memur   Kayseri        4200
2       3    Timur   30     Müzisyen  Istanbul        9000
3       4    Burcu   29  Pazarlamaci    Ankara        4200
4       5  Yasemin   23          NaN     Bursa        4800

In [23]:
df['sirano'].head()

0    1
1    2
2    3
3    4
4    5
Name: sirano, dtype: int64

In [24]:
type(df['sirano'])

pandas.core.series.Series

In [26]:
df[['sirano','meslek']].head()

   sirano       meslek
0       1         Isci
1       2        Memur
2       3     Müzisyen
3       4  Pazarlamaci
4       5          NaN

In [29]:
#mevcut sütun degerini degiştirmek
df["aylikgelir"] = df["aylikgelir"] + 1000

In [30]:
df.head()

   sirano       ad  yas       meslek     sehir  aylikgelir
0       1    Cemal   35         Isci    Ankara        4500
1       2    Ceyda   42        Memur   Kayseri        5200
2       3    Timur   30     Müzisyen  Istanbul       10000
3       4    Burcu   29  Pazarlamaci    Ankara        5200
4       5  Yasemin   23          NaN     Bursa        5800

In [31]:
#yeni sütun eklemek
df["aylik_gelir_dolar"] = df["aylikgelir"] * 19.7

In [32]:
df.head()

   sirano       ad  yas       meslek     sehir  aylikgelir  aylik_gelir_dolar
0       1    Cemal   35         Isci    Ankara        4500            88650.0
1       2    Ceyda   42        Memur   Kayseri        5200           102440.0
2       3    Timur   30     Müzisyen  Istanbul       10000           197000.0
3       4    Burcu   29  Pazarlamaci    Ankara        5200           102440.0
4       5  Yasemin   23          NaN     Bursa        5800           114260.0

In [33]:
#kategorik değişken üreterek yeni sütun oluşturmak

op_labels = ["low", "middle", "high"]
category = [0, 5000,8000, 100000]
df["gelir_seviyesi"] = pd.cut(df["aylikgelir"], bins=category, labels=op_labels,include_lowest=False)

In [34]:
df.head()

,sirano,ad,yas,meslek,sehir,aylikgelir,aylik_gelir_dolar,gelir_seviyesi
0,1,Cemal,35,Isci,Ankara,4500,88650.0,low
1,2,Ceyda,42,Memur,Kayseri,5200,102440.0,middle
2,3,Timur,30,Müzisyen,Istanbul,10000,197000.0,high
3,4,Burcu,29,Pazarlamaci,Ankara,5200,102440.0,middle
4,5,Yasemin,23,NaN,Bursa,5800,114260.0,middle

In [35]:
#sütunları birleştirmek
df["gelir_seviyesi"] = df["aylikgelir"].astype(str) + " - " + df["gelir_seviyesi"].astype(str)

In [36]:
df.head()

,sirano,ad,yas,meslek,sehir,aylikgelir,aylik_gelir_dolar,gelir_seviyesi
0,1,Cemal,35,Isci,Ankara,4500,88650.0,4500 - low
1,2,Ceyda,42,Memur,Kayseri,5200,102440.0,5200 - middle
2,3,Timur,30,Müzisyen,Istanbul,10000,197000.0,10000 - high
3,4,Burcu,29,Pazarlamaci,Ankara,5200,102440.0,5200 - middle
4,5,Yasemin,23,NaN,Bursa,5800,114260.0,5800 - middle

In [37]:
#her benzersiz satır için id oluşturmak
len(df)

17

In [38]:
df["id"] = list(range(100001,100018))

In [39]:
df.head()

,sirano,ad,yas,meslek,sehir,aylikgelir,aylik_gelir_dolar,gelir_seviyesi,id
0,1,Cemal,35,Isci,Ankara,4500,88650.0,4500 - low,100001
1,2,Ceyda,42,Memur,Kayseri,5200,102440.0,5200 - middle,100002
2,3,Timur,30,Müzisyen,Istanbul,10000,197000.0,10000 - high,100003
3,4,Burcu,29,Pazarlamaci,Ankara,5200,102440.0,5200 - middle,100004
4,5,Yasemin,23,NaN,Bursa,5800,114260.0,5800 - middle,100005

In [42]:
#sütunların sırasnı değiştirmek

df.rename(columns = {'isim' : 'ad', 'sehir' : 'il'}, inplace=True)
#

In [43]:
df.head()

,sirano,ad,yas,meslek,il,aylikgelir,aylik_gelir_dolar,gelir_seviyesi,id
0,1,Cemal,35,Isci,Ankara,4500,88650.0,4500 - low,100001
1,2,Ceyda,42,Memur,Kayseri,5200,102440.0,5200 - middle,100002
2,3,Timur,30,Müzisyen,Istanbul,10000,197000.0,10000 - high,100003
3,4,Burcu,29,Pazarlamaci,Ankara,5200,102440.0,5200 - middle,100004
4,5,Yasemin,23,NaN,Bursa,5800,114260.0,5800 - middle,100005

In [45]:
df.columns

Index(['sirano', 'ad', 'yas', 'meslek', 'il', 'aylikgelir',
       'aylik_gelir_dolar', 'gelir_seviyesi', 'id'],
      dtype='object')

In [46]:
df = df[['id','sirano', 'ad', 'yas', 'meslek', 'il', 'aylikgelir',
       'aylik_gelir_dolar', 'gelir_seviyesi']]

In [47]:
df.head()

,id,sirano,ad,yas,meslek,il,aylikgelir,aylik_gelir_dolar,gelir_seviyesi
0,100001,1,Cemal,35,Isci,Ankara,4500,88650.0,4500 - low
1,100002,2,Ceyda,42,Memur,Kayseri,5200,102440.0,5200 - middle
2,100003,3,Timur,30,Müzisyen,Istanbul,10000,197000.0,10000 - high
3,100004,4,Burcu,29,Pazarlamaci,Ankara,5200,102440.0,5200 - middle
4,100005,5,Yasemin,23,NaN,Bursa,5800,114260.0,5800 - middle