<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/pandas_s%C4%B1ralama_filteleme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
! curl -o simple_data.csv https://raw.githubusercontent.com/erkansirin78/datasets/master/simple_data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   592  100   592    0     0   1303      0 --:--:-- --:--:-- --:--:--  1306

In [3]:
df = pd.read_csv('simple_data.csv')

In [4]:
df.head()

   sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23          NaN     Bursa         4800

In [5]:
#sıralama
df = pd.read_csv("simple_data.csv")

In [6]:
df.head()

   sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23          NaN     Bursa         4800

In [7]:
df.sort_values(by='aylik_gelir')

    sirano      isim  yas       meslek     sehir  aylik_gelir
0        1     Cemal   35         Isci    Ankara         3500
12      13     Hakkı   33        Memur     Çorum         3750
3        4     Burcu   29  Pazarlamaci    Ankara         4200
1        2     Ceyda   42        Memur   Kayseri         4200
11      12     Harun   43      Tornacı    Ankara         4200
5        6       Ali   33        Memur    Ankara         4250
4        5   Yasemin   23          NaN     Bursa         4800
10      11  Hicaziye   47   Tuhafiyeci    Ankara         4800
6        7     Dilek   29  Pazarlamaci  Istanbul         7300
14      15    Şehmuz   41          NaN    Ankara         8700
15      16    Gençay   46       Berber    Ankara         8800
16      16    Gençay   46       Berber    Ankara         8800
2        3     Timur   30     Müzisyen  Istanbul         9000
7        8     Murat   31     Müzisyen  Istanbul        12000
9       10  Muhittin   46       Berber  Istanbul        12000
13      14   Gülizar   37       Doktor     İzmir        14250
8        9     Ahmet   33       Doktor    Ankara        18000

In [8]:
df.sort_values(by='aylik_gelir',ascending = False) #azalan sıralama

    sirano      isim  yas       meslek     sehir  aylik_gelir
8        9     Ahmet   33       Doktor    Ankara        18000
13      14   Gülizar   37       Doktor     İzmir        14250
9       10  Muhittin   46       Berber  Istanbul        12000
7        8     Murat   31     Müzisyen  Istanbul        12000
2        3     Timur   30     Müzisyen  Istanbul         9000
16      16    Gençay   46       Berber    Ankara         8800
15      16    Gençay   46       Berber    Ankara         8800
14      15    Şehmuz   41          NaN    Ankara         8700
6        7     Dilek   29  Pazarlamaci  Istanbul         7300
4        5   Yasemin   23          NaN     Bursa         4800
10      11  Hicaziye   47   Tuhafiyeci    Ankara         4800
5        6       Ali   33        Memur    Ankara         4250
1        2     Ceyda   42        Memur   Kayseri         4200
11      12     Harun   43      Tornacı    Ankara         4200
3        4     Burcu   29  Pazarlamaci    Ankara         4200
12      13     Hakkı   33        Memur     Çorum         3750
0        1     Cemal   35         Isci    Ankara         3500

In [11]:
df.sort_values(by=["aylik_gelir","yas"])#aylik gelir aynı olanlarda yas küçükten büyüğe getiriyor

    sirano      isim  yas       meslek     sehir  aylik_gelir
0        1     Cemal   35         Isci    Ankara         3500
12      13     Hakkı   33        Memur     Çorum         3750
3        4     Burcu   29  Pazarlamaci    Ankara         4200
1        2     Ceyda   42        Memur   Kayseri         4200
11      12     Harun   43      Tornacı    Ankara         4200
5        6       Ali   33        Memur    Ankara         4250
4        5   Yasemin   23          NaN     Bursa         4800
10      11  Hicaziye   47   Tuhafiyeci    Ankara         4800
6        7     Dilek   29  Pazarlamaci  Istanbul         7300
14      15    Şehmuz   41          NaN    Ankara         8700
15      16    Gençay   46       Berber    Ankara         8800
16      16    Gençay   46       Berber    Ankara         8800
2        3     Timur   30     Müzisyen  Istanbul         9000
7        8     Murat   31     Müzisyen  Istanbul        12000
9       10  Muhittin   46       Berber  Istanbul        12000
13      14   Gülizar   37       Doktor     İzmir        14250
8        9     Ahmet   33       Doktor    Ankara        18000

In [13]:
df[df['meslek'] == 'Doktor'] #filtereleme

    sirano     isim  yas  meslek   sehir  aylik_gelir
8        9    Ahmet   33  Doktor  Ankara        18000
13      14  Gülizar   37  Doktor   İzmir        14250

In [14]:
df[(df['meslek'] == "Müzisyen")& (df['aylik_gelir']> 10000)]

   sirano   isim  yas    meslek     sehir  aylik_gelir
7       8  Murat   31  Müzisyen  Istanbul        12000

In [15]:
df[(df['meslek']== "Müzisyen")|(df['meslek']=='Berber')]

    sirano      isim  yas    meslek     sehir  aylik_gelir
2        3     Timur   30  Müzisyen  Istanbul         9000
7        8     Murat   31  Müzisyen  Istanbul        12000
9       10  Muhittin   46    Berber  Istanbul        12000
15      16    Gençay   46    Berber    Ankara         8800
16      16    Gençay   46    Berber    Ankara         8800

In [17]:
#query metodu ile sql where tarzı filtreleme
df.query("meslek == 'Doktor' | aylik_gelir > 10000").sort_values(by='aylik_gelir')

    sirano      isim  yas    meslek     sehir  aylik_gelir
7        8     Murat   31  Müzisyen  Istanbul        12000
9       10  Muhittin   46    Berber  Istanbul        12000
13      14   Gülizar   37    Doktor     İzmir        14250
8        9     Ahmet   33    Doktor    Ankara        18000

In [18]:
#unique() ile benzersiz kategorileri elde etme
df.meslek.unique()

array(['Isci', 'Memur', 'Müzisyen', 'Pazarlamaci', nan, 'Doktor',
       'Berber', 'Tuhafiyeci', 'Tornacı'], dtype=object)

In [19]:
#distinct count
len(df.meslek.unique())

9