<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/06_pandas_string_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/OnlineRetail2.csv

--2026-03-20 18:47:45--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/OnlineRetail2.csv
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/OnlineRetail2.csv [following]
--2026-03-20 18:47:45--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/OnlineRetail2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48039726 (46M) [text/plain]
Saving to: ‘OnlineRetail2.csv’

OnlineRetail2.csv   100%[===================>]  45.81M  --.-KB/s    in 0.1s

2026-03-20 18:47:47 (324 MB/s) - ‘OnlineRetail2.csv’ saved [48039726/48039726]

In [4]:
df = pd.read_csv("OnlineRetail2.csv")

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [6]:
#upper() country büyük harf

df.Country.str.upper().head()

0    UNITED KINGDOM
1    UNITED KINGDOM
2    UNITED KINGDOM
3    UNITED KINGDOM
4    UNITED KINGDOM
Name: Country, dtype: object

In [7]:
df['Country'] = df.Country.str.upper()

In [9]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,UNITED KINGDOM
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,UNITED KINGDOM
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,UNITED KINGDOM
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,UNITED KINGDOM
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,UNITED KINGDOM

In [10]:
#contains içerenler , startswith() ile başlayanlar

df[df.Description.str.contains("COFFEE",na=False)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
53,536373,37370,RETRO COFFEE MUGS ASSORTED,6,2010-12-01 09:02:00,1.06,17850.0,UNITED KINGDOM
70,536375,37370,RETRO COFFEE MUGS ASSORTED,6,2010-12-01 09:32:00,1.06,17850.0,UNITED KINGDOM
283,536396,37370,RETRO COFFEE MUGS ASSORTED,6,2010-12-01 10:51:00,1.06,17850.0,UNITED KINGDOM
420,536406,37370,RETRO COFFEE MUGS ASSORTED,6,2010-12-01 11:33:00,1.06,17850.0,UNITED KINGDOM
1044,536522,37370,RETRO COFFEE MUGS ASSORTED,2,2010-12-01 12:49:00,1.25,15012.0,UNITED KINGDOM

In [12]:
df[df.InvoiceNo.str.contains("C",na=False)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,UNITED KINGDOM
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,UNITED KINGDOM
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,UNITED KINGDOM
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,UNITED KINGDOM
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,UNITED KINGDOM
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,UNITED KINGDOM
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,UNITED KINGDOM
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,UNITED KINGDOM
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,UNITED KINGDOM
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,UNITED KINGDOM

In [13]:
df[df.InvoiceNo.str.startswith("C")].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,UNITED KINGDOM
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,UNITED KINGDOM
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,UNITED KINGDOM
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,UNITED KINGDOM
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,UNITED KINGDOM

In [14]:
#replace yer değiştirme
#Bir sütun içinde geçen örüntüyü değiştirme
df['Description'] = df ['Description'].replace({'RETRO': 'COSTA'}, regex = True)
df[df.Description.str.contains("COFFEE",na=False)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
53,536373,37370,COSTA COFFEE MUGS ASSORTED,6,2010-12-01 09:02:00,1.06,17850.0,UNITED KINGDOM
70,536375,37370,COSTA COFFEE MUGS ASSORTED,6,2010-12-01 09:32:00,1.06,17850.0,UNITED KINGDOM
283,536396,37370,COSTA COFFEE MUGS ASSORTED,6,2010-12-01 10:51:00,1.06,17850.0,UNITED KINGDOM
420,536406,37370,COSTA COFFEE MUGS ASSORTED,6,2010-12-01 11:33:00,1.06,17850.0,UNITED KINGDOM
1044,536522,37370,COSTA COFFEE MUGS ASSORTED,2,2010-12-01 12:49:00,1.25,15012.0,UNITED KINGDOM

In [15]:
#bir sütunda birden fazla örüntüyü değiştirme
df['Description'] = df ['Description'].replace({'RETRO': 'COSTA','MUGS':'MOCHA'}, regex = True)
df[df.Description.str.contains("COFFEE",na=False)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
53,536373,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 09:02:00,1.06,17850.0,UNITED KINGDOM
70,536375,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 09:32:00,1.06,17850.0,UNITED KINGDOM
283,536396,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 10:51:00,1.06,17850.0,UNITED KINGDOM
420,536406,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 11:33:00,1.06,17850.0,UNITED KINGDOM
1044,536522,37370,COSTA COFFEE MOCHA ASSORTED,2,2010-12-01 12:49:00,1.25,15012.0,UNITED KINGDOM

In [16]:
#nokta olarak bir hücreyi güncelleme (değer atama)
df.at[53,'StockCode']='37371'
df[df.Description.str.contains("COFFEE",na=False)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
53,536373,37371,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 09:02:00,1.06,17850.0,UNITED KINGDOM
70,536375,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 09:32:00,1.06,17850.0,UNITED KINGDOM
283,536396,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 10:51:00,1.06,17850.0,UNITED KINGDOM
420,536406,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01 11:33:00,1.06,17850.0,UNITED KINGDOM
1044,536522,37370,COSTA COFFEE MOCHA ASSORTED,2,2010-12-01 12:49:00,1.25,15012.0,UNITED KINGDOM

In [17]:
#sütunu truncate etmek
df["InvoiceDate"] = df["InvoiceDate"].apply(lambda x : x[:-9])
df[df.Description.str.contains("COFFEE",na=False)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
53,536373,37371,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01,1.06,17850.0,UNITED KINGDOM
70,536375,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01,1.06,17850.0,UNITED KINGDOM
283,536396,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01,1.06,17850.0,UNITED KINGDOM
420,536406,37370,COSTA COFFEE MOCHA ASSORTED,6,2010-12-01,1.06,17850.0,UNITED KINGDOM
1044,536522,37370,COSTA COFFEE MOCHA ASSORTED,2,2010-12-01,1.25,15012.0,UNITED KINGDOM