<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/07_pandas_gruplama_s%C4%B1ralama.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/simple_data.csv

--2026-03-21 13:20:11--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/simple_data.csv
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/simple_data.csv [following]
--2026-03-21 13:20:12--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/simple_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 592 [text/plain]
Saving to: ‘simple_data.csv’

simple_data.csv     100%[===================>]     592  --.-KB/s    in 0s

2026-03-21 13:20:12 (21.7 MB/s) - ‘simple_data.csv’ saved [592/592]

In [4]:
df = pd.read_csv("simple_data.csv")

In [5]:
df.head()

   sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23          NaN     Bursa         4800

In [ ]:
#df.groupby(['cat_col1']).agg.col.agg(['agg_func1', 'agg_func2'])

In [7]:
meslek_grupby = df.groupby(['meslek']).aylik_gelir.agg(['mean']).head()

In [8]:
#indeks kullanara yeni sütun yaratma
meslek_grupby.reset_index(inplace=True)

In [9]:
meslek_grupby.head()

     meslek          mean
0    Berber   9866.666667
1    Doktor  16125.000000
2      Isci   3500.000000
3     Memur   4066.666667
4  Müzisyen  10500.000000

In [13]:
#meslekleri ortalama kazançlarına göre sıralama
df.groupby(['meslek']).aylik_gelir.agg(['mean']).sort_values(by="mean", ascending = False).head()

                     mean
meslek
Doktor       16125.000000
Müzisyen     10500.000000
Berber        9866.666667
Pazarlamaci   5750.000000
Tuhafiyeci    4800.000000

In [16]:
 #birden fazla niteliği gruplama ve birden g-fazla nitelik üzerinde kümeleme
 #fonksiyonu çalıştırma
 df.groupby(['meslek']).aylik_gelir.agg(['mean','sum','count']).sort_values("count", ascending=False).head()

                     mean    sum  count
meslek
Berber        9866.666667  29600      3
Memur         4066.666667  12200      3
Doktor       16125.000000  32250      2
Müzisyen     10500.000000  21000      2
Pazarlamaci   5750.000000  11500      2

In [18]:
#birden fazla sıralama nasıl olur
df.sort_values(['yas','aylik_gelir'],ascending=False).head()

    sirano      isim  yas      meslek     sehir  aylik_gelir
10      11  Hicaziye   47  Tuhafiyeci    Ankara         4800
9       10  Muhittin   46      Berber  Istanbul        12000
15      16    Gençay   46      Berber    Ankara         8800
16      16    Gençay   46      Berber    Ankara         8800
11      12     Harun   43     Tornacı    Ankara         4200

In [20]:
#birden fazla nümerik deper üzerinde groupby()
df.groupby(["meslek"])[["yas","aylik_gelir"]].agg(["mean","sum","count"]).head()

           yas              aylik_gelir
          mean  sum count          mean    sum count
meslek
Berber    46.0  138     3   9866.666667  29600     3
Doktor    35.0   70     2  16125.000000  32250     2
Isci      35.0   35     1   3500.000000   3500     1
Memur     36.0  108     3   4066.666667  12200     3
Müzisyen  30.5   61     2  10500.000000  21000     2

In [24]:
#çoklu sütun indeksnde sıralama (MultiIndex) #aylik gelir meana  gör sıraladık
df.groupby(["meslek"])[["yas","aylik_gelir"]].agg(["mean","sum","count"])\
.sort_values([('aylik_gelir','mean')], ascending=False) \
.head()

              yas              aylik_gelir
             mean  sum count          mean    sum count
meslek
Doktor       35.0   70     2  16125.000000  32250     2
Müzisyen     30.5   61     2  10500.000000  21000     2
Berber       46.0  138     3   9866.666667  29600     3
Pazarlamaci  29.0   58     2   5750.000000  11500     2
Tuhafiyeci   47.0   47     1   4800.000000   4800     1