<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/10_pandas_sql_like.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np

In [1]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/tips.csv

--2026-03-21 17:25:20--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/tips.csv
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/tips.csv [following]
--2026-03-21 17:25:20--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/tips.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7942 (7.8K) [text/plain]
Saving to: ‘tips.csv’

tips.csv            100%[===================>]   7.76K  --.-KB/s    in 0s

2026-03-21 17:25:20 (71.3 MB/s) - ‘tips.csv’ saved [7942/7942]

In [4]:
df = pd.read_csv('tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

SELECT

SELECT total_bill, tip, smoker, time
    FROM tips
    LIMIT 5;

In [5]:
df[['total_bill','tip','smoker','time']].head(5)

   total_bill   tip smoker    time
0       16.99  1.01     No  Dinner
1       10.34  1.66     No  Dinner
2       21.01  3.50     No  Dinner
3       23.68  3.31     No  Dinner
4       24.59  3.61     No  Dinner

WHERE

    SELECT * FROM tips
    WHERE time = 'Dinner'
    LIMIT 5;

In [7]:
df[df['time'].str.contains('Dinner')].head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

YA DA

In [9]:
df[df['time'] == 'Dinner'].head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

SELECT *
    FROM tips
    WHERE time = 'Dinner' AND tip > 5.00;

In [16]:
df[ (df.time == 'Dinner' ) & (df.tip >5.00)].head(5)

    total_bill   tip     sex smoker  day    time  size
23       39.42  7.58    Male     No  Sat  Dinner     4
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4
52       34.81  5.20  Female     No  Sun  Dinner     4
59       48.27  6.73    Male     No  Sat  Dinner     4

 SELECT day, avg(total_bill) as total_bill, avg(tip) as tip
    FROM tips
    GROUP BY day;

In [18]:
df.groupby(['day'])[['total_bill','tip']].mean().reset_index()

    day  total_bill       tip
0   Fri   17.151579  2.734737
1   Sat   20.441379  2.993103
2   Sun   21.410000  3.255132
3  Thur   17.682742  2.771452

In [20]:
df.groupby(['day'])[['total_bill','tip']].agg(['mean']).reset_index()

    day total_bill       tip
              mean      mean
0   Fri  17.151579  2.734737
1   Sat  20.441379  2.993103
2   Sun  21.410000  3.255132
3  Thur  17.682742  2.771452

    SELECT day, AVG(tip), COUNT(*)
    FROM tips
    GROUP BY day;

In [22]:
df.groupby('day')['tip'].agg(['mean','count']).head()

          mean  count
day
Fri   2.734737     19
Sat   2.993103     87
Sun   3.255132     76
Thur  2.771452     62

YA DA

In [24]:
df.groupby(['day']).agg({'tip':np.mean, 'day' : np.size})

/tmp/ipykernel_7239/1111528295.py:1: FutureWarning: The provided callable <function mean at 0x7cba6b1294e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['day']).agg({'tip':np.mean, 'day' : np.size})

           tip  day
day
Fri   2.734737   19
Sat   2.993103   87
Sun   3.255132   76
Thur  2.771452   62

SELECT smoker, day, COUNT(*), AVG(tip)
    FROM tips
    GROUP BY smoker, day;

In [27]:
df.groupby(['smoker','day'])['tip'].agg(['mean','count'])

                 mean  count
smoker day
No     Fri   2.812500      4
       Sat   3.102889     45
       Sun   3.167895     57
       Thur  2.673778     45
Yes    Fri   2.714000     15
       Sat   2.875476     42
       Sun   3.516842     19
       Thur  3.030000     17

YA DA

In [28]:
df.groupby(['smoker','day']).agg({'tip':[np.size,np.mean]}).sort_values('day')

/tmp/ipykernel_7239/24410760.py:1: FutureWarning: The provided callable <function mean at 0x7cba6b1294e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['smoker','day']).agg({'tip':[np.size,np.mean]}).sort_values('day')

             tip
            size      mean
smoker day
No     Fri     4  2.812500
Yes    Fri    15  2.714000
No     Sat    45  3.102889
Yes    Sat    42  2.875476
No     Sun    57  3.167895
Yes    Sun    19  3.516842
No     Thur   45  2.673778
Yes    Thur   17  3.030000

UPDATE

 UPDATE tips
    SET tip = tip*1000
    WHERE tip < 2;

In [29]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
df.loc[df['tip'] < 2, 'tip'] *= 1000

In [31]:
df.head()

   total_bill      tip     sex smoker  day    time  size
0       16.99  1010.00  Female     No  Sun  Dinner     2
1       10.34  1660.00    Male     No  Sun  Dinner     3
2       21.01     3.50    Male     No  Sun  Dinner     3
3       23.68     3.31    Male     No  Sun  Dinner     2
4       24.59     3.61  Female     No  Sun  Dinner     4

DELETE

DELETE FROM tips
    WHERE tip > 1000;

In [35]:
df = df.loc[df['tip'] < 1000] #1000 den küçükleri df atadığım için silinmiş oldu

In [37]:
df.sort_values(by='tip', ascending=False)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
..          ...    ...     ...    ...   ...     ...   ...
202       13.00   2.00  Female    Yes  Thur   Lunch     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
226       10.09   2.00  Female    Yes   Fri   Lunch     2
240       27.18   2.00  Female    Yes   Sat  Dinner     2
241       22.67   2.00    Male    Yes   Sat  Dinner     2

[199 rows x 7 columns]

In [38]:
df.loc[df['tip'] > 1000].head()

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size]
Index: []