<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/pandas_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas Homework

## 1.
Using https://raw.githubusercontent.com/erkansirin78/datasets/master/simple_data.csv dataset;

### 1.1.
Capitalize column names

### 1.2.
Combine the occupation, city columns in a new column with a line between them.

### 1.3.
Calculate monthly_income in dollars and add a new column named monthly_income_dollars.

### 1.4.
- Starting from 3801 and incrementing 3802, 3803... give each row an id number (in a new column)
- Based on monthly_income, 0-2500 as low, 2500-7500 as medium and above 7500 as high categorize it and add it as a new column with the name income_category.

## 2.
On the Advertising.csv dataset

### 2.1.
Sort descending by Sales

### 2.2.
Recordings with a TV budget of less than 50

### 2.3.
Sort the recordings with a TV budget less than 50 in descending order of Sales.

In [1]:
import pandas as pd

In [2]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/simple_data.csv

--2026-03-21 18:21:47--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/simple_data.csv
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/simple_data.csv [following]
--2026-03-21 18:21:47--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/simple_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 592 [text/plain]
Saving to: ‘simple_data.csv’

simple_data.csv     100%[===================>]     592  --.-KB/s    in 0s

2026-03-21 18:21:47 (27.3 MB/s) - ‘simple_data.csv’ saved [592/592]

## 1.
Using https://raw.githubusercontent.com/erkansirin78/datasets/master/simple_data.csv dataset;

In [3]:
df = pd.read_csv("simple_data.csv")

In [4]:
df.head()

   sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23          NaN     Bursa         4800

### 1.1.
Capitalize column names

In [12]:
df.columns = df.columns.str.upper()

In [13]:
df.head()

   SIRANO     ISIM  YAS       MESLEK     SEHIR  AYLIK_GELIR
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23          NaN     Bursa         4800

### 1.2.
Combine the occupation, city columns in a new column with a line between them.

In [17]:
df["MESLEK-SEHİR"] = df["MESLEK"] + "-" + df["SEHIR"]

In [18]:
df.head()

,SIRANO,ISIM,YAS,MESLEK,SEHIR,AYLIK_GELIR,MESLEK-SEHİR
0,1,Cemal,35,Isci,Ankara,3500,Isci-Ankara
1,2,Ceyda,42,Memur,Kayseri,4200,Memur-Kayseri
2,3,Timur,30,Müzisyen,Istanbul,9000,Müzisyen-Istanbul
3,4,Burcu,29,Pazarlamaci,Ankara,4200,Pazarlamaci-Ankara
4,5,Yasemin,23,NaN,Bursa,4800,NaN

### 1.3.
Calculate monthly_income in dollars and add a new column named monthly_income_dollars.

In [19]:
df["AYLIK_GELIR_DOLAR"] = df["AYLIK_GELIR"] * 44

In [20]:
df.head()

,SIRANO,ISIM,YAS,MESLEK,SEHIR,AYLIK_GELIR,MESLEK-SEHİR,AYLIK_GELIR_DOLAR
0,1,Cemal,35,Isci,Ankara,3500,Isci-Ankara,154000
1,2,Ceyda,42,Memur,Kayseri,4200,Memur-Kayseri,184800
2,3,Timur,30,Müzisyen,Istanbul,9000,Müzisyen-Istanbul,396000
3,4,Burcu,29,Pazarlamaci,Ankara,4200,Pazarlamaci-Ankara,184800
4,5,Yasemin,23,NaN,Bursa,4800,NaN,211200

### 1.4.
- Starting from 3801 and incrementing 3802, 3803... give each row an id number (in a new column)
- Based on monthly_income, 0-2500 as low, 2500-7500 as medium and above 7500 as high categorize it and add it as a new column with the name income_category.

In [24]:
df["ID"] = range(3801, 3801 + len(df))

In [25]:
df.head()

,SIRANO,ISIM,YAS,MESLEK,SEHIR,AYLIK_GELIR,MESLEK-SEHİR,AYLIK_GELIR_DOLAR,ID
0,1,Cemal,35,Isci,Ankara,3500,Isci-Ankara,154000,3801
1,2,Ceyda,42,Memur,Kayseri,4200,Memur-Kayseri,184800,3802
2,3,Timur,30,Müzisyen,Istanbul,9000,Müzisyen-Istanbul,396000,3803
3,4,Burcu,29,Pazarlamaci,Ankara,4200,Pazarlamaci-Ankara,184800,3804
4,5,Yasemin,23,NaN,Bursa,4800,NaN,211200,3805

In [26]:
def kategori(x):
  if x < 2500:
    return "low"
  elif x<=7500:
    return"medium"
  else:
    return "high"

df["INCOME_CATEGORY"] = df["AYLIK_GELIR"].apply(kategori)
df.head()

,SIRANO,ISIM,YAS,MESLEK,SEHIR,AYLIK_GELIR,MESLEK-SEHİR,AYLIK_GELIR_DOLAR,ID,INCOME_CATEGORY
0,1,Cemal,35,Isci,Ankara,3500,Isci-Ankara,154000,3801,medium
1,2,Ceyda,42,Memur,Kayseri,4200,Memur-Kayseri,184800,3802,medium
2,3,Timur,30,Müzisyen,Istanbul,9000,Müzisyen-Istanbul,396000,3803,high
3,4,Burcu,29,Pazarlamaci,Ankara,4200,Pazarlamaci-Ankara,184800,3804,medium
4,5,Yasemin,23,NaN,Bursa,4800,NaN,211200,3805,medium

Ya DA

In [28]:
df["INCOME_CATEGORY2"] = pd.cut(df["AYLIK_GELIR"], bins =[0,2500,7500,float("inf")],labels = ["low","medium","high"])
#inf sonsuz demek

In [29]:
df.head()

,SIRANO,ISIM,YAS,MESLEK,SEHIR,AYLIK_GELIR,MESLEK-SEHİR,AYLIK_GELIR_DOLAR,ID,INCOME_CATEGORY,INCOME_CATEGORY2
0,1,Cemal,35,Isci,Ankara,3500,Isci-Ankara,154000,3801,medium,medium
1,2,Ceyda,42,Memur,Kayseri,4200,Memur-Kayseri,184800,3802,medium,medium
2,3,Timur,30,Müzisyen,Istanbul,9000,Müzisyen-Istanbul,396000,3803,high,high
3,4,Burcu,29,Pazarlamaci,Ankara,4200,Pazarlamaci-Ankara,184800,3804,medium,medium
4,5,Yasemin,23,NaN,Bursa,4800,NaN,211200,3805,medium,medium

## 2.
On the Advertising.csv dataset

In [30]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/Advertising.csv

--2026-03-21 19:12:04--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/Advertising.csv
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/Advertising.csv [following]
--2026-03-21 19:12:04--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/Advertising.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4556 (4.4K) [text/plain]
Saving to: ‘Advertising.csv’

Advertising.csv     100%[===================>]   4.45K  --.-KB/s    in 0s

2026-03-21 19:12:04 (29.1 MB/s) - ‘Advertising.csv’ saved [4556/4556]

In [31]:
df2 = pd.read_csv("Advertising.csv")

In [32]:
df2.head()

   ID     TV  Radio  Newspaper  Sales
0   1  230.1   37.8       69.2   22.1
1   2   44.5   39.3       45.1   10.4
2   3   17.2   45.9       69.3    9.3
3   4  151.5   41.3       58.5   18.5
4   5  180.8   10.8       58.4   12.9

### 2.1.
Sort descending by Sales

In [33]:
df2.sort_values("Sales", ascending = False)

      ID     TV  Radio  Newspaper  Sales
175  176  276.9   48.9       41.8   27.0
183  184  287.6   43.0       71.8   26.2
198  199  283.6   42.0       66.2   25.5
36    37  266.9   43.8        5.0   25.4
98    99  289.7   42.3       51.2   25.4
..   ...    ...    ...        ...    ...
78    79    5.4   29.9        9.4    5.3
108  109   13.1    0.4       25.6    5.3
8      9    8.6    2.1        1.0    4.8
155  156    4.1   11.6        5.7    3.2
130  131    0.7   39.6        8.7    1.6

[200 rows x 5 columns]

### 2.2.
Recordings with a TV budget of less than 50

In [38]:
df2[df2["TV"]< 50 ]

      ID    TV  Radio  Newspaper  Sales
1      2  44.5   39.3       45.1   10.4
2      3  17.2   45.9       69.3    9.3
5      6   8.7   48.9       75.0    7.2
8      9   8.6    2.1        1.0    4.8
12    13  23.8   35.1       65.9    9.2
22    23  13.2   15.9       49.6    5.6
38    39  43.1   26.7       35.1   10.1
44    45  25.1   25.7       43.3    8.5
56    57   7.3   28.1       41.4    5.5
66    67  31.5   24.6        2.2    9.5
72    73  26.8   33.0       19.3    8.8
75    76  16.9   43.7       89.4    8.7
76    77  27.5    1.6       20.7    6.9
78    79   5.4   29.9        9.4    5.3
91    92  28.6    1.5       33.0    7.3
106  107  25.0   11.0       29.7    7.2
108  109  13.1    0.4       25.6    5.3
119  120  19.4   16.0       22.3    6.6
121  122  18.8   21.7       50.4    7.0
126  127   7.8   38.9       50.6    6.6
130  131   0.7   39.6        8.7    1.6
132  133   8.4   27.2        2.1    5.7
134  135  36.9   38.6       65.6   10.8
135  136  48.3   47.0        8.5   11.6
136  137  25.6   39.0        9.3    9.5
138  139  43.0   25.9       20.5    9.6
148  149  38.0   40.3       11.9   10.9
149  150  44.7   25.8       20.6   10.1
155  156   4.1   11.6        5.7    3.2
158  159  11.7   36.9       45.2    7.3
166  167  17.9   37.6       21.6    8.0
172  173  19.6   20.1       17.0    7.6
189  190  18.7   12.1       23.4    6.7
190  191  39.5   41.1        5.8   10.8
192  193  17.2    4.1       31.6    5.9
195  196  38.2    3.7       13.8    7.6

In [35]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         200 non-null    int64
 1   TV         200 non-null    float64
 2   Radio      200 non-null    float64
 3   Newspaper  200 non-null    float64
 4   Sales      200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

### 2.3.
Sort the recordings with a TV budget less than 50 in descending order of Sales.

In [43]:
df2[df2["TV"] <50].sort_values(by="Sales", ascending=False).head()

      ID    TV  Radio  Newspaper  Sales
135  136  48.3   47.0        8.5   11.6
148  149  38.0   40.3       11.9   10.9
134  135  36.9   38.6       65.6   10.8
190  191  39.5   41.1        5.8   10.8
1      2  44.5   39.3       45.1   10.4